settings:
  title: "didingqd'监测站"
  url: 'https://upflare.ddqd.us.kg' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有服务均Active'
  notAllmonitorsOperational: '有服务未Active'
  monitorLabelOperational: 'Active'
  monitorLabelNotOperational: 'No Active'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '非常好'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: baidu
    name: 百度
    description: '测试'
    url: 'https://www.baidu.com'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: card-tab
    name: 导航站
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://card.ddqd.us.kg' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-1-serv00
    name: didingqd's blog
    description: '我的博客'
    url: 'https://blog.ddqd.us.kg'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-2
    name: ddqd's blog
    description: '我的第二博客'
    url: 'https://blog.ddqd.nyc.mn'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 苹果CMS-1
    name: 苹果CMS（香港）
    description: '我的影视站'
    url: 'https://cms.ddq.us.kg'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: 苹果CMS-2
    name: 苹果CMS（波兰）
    description: '我的影视站'
    url: 'https://cms.techdd.us.kg'
    method: GET
    expectStatus: 200
    linkable: false   
